apiVersion: v2
name: openebs-monitoring
description: A Helm chart for monitoring OpenEBS

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

maintainers:
  - name: kiranmova
    email: kiran.mova@mayadata.io
  - name: avishnu
    email: vishnu.attur@mayadata.io
  - name: Ab-hishek
    email: abhishek.agarwal@mayadata.io
  - name: rajaSahil
    email: sahil.raja@mayadata.io
  - name: Sanjay1611
    email: sanjay.nathani@mayadata.io

sources:
  - https://github.com/openebs/monitoring

keywords:
  - openebs
  - monitoring

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 2.9.0

dependencies:
  - name: kube-prometheus-stack
    version: "16.5.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.install
