{{- if .Values.podMonitors }}
{{- range $openebsEngine, $fields := .Values.podMonitors }}
{{- if (and (hasKey $fields "enabled") ($fields.enabled)) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ lower (printf "%s-%s" (include "openebs-monitoring.fullname" $) $openebsEngine) | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "openebs-monitoring.namespace" $ }}
  labels:
    app: {{ template "openebs-monitoring.name" $ }}-{{ $openebsEngine }}
{{ include "openebs-monitoring.labels" $ | indent 4 }}
spec:
  selector:
{{ toYaml $fields.selector | indent 4 }}
  namespaceSelector:
{{ toYaml $fields.namespaceSelector | indent 4 }}
  podMetricsEndpoints:
    - targetPort: {{ $fields.podMetricsEndpoints.targetPort }}
      path: {{ $fields.podMetricsEndpoints.path }}
{{- if $fields.podMetricsEndpoints.relabelings }}
      relabelings:
{{ toYaml $fields.podMetricsEndpoints.relabelings | indent 8 }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
