{{- if .Values.serviceMonitors }}
{{- range $openebsEngine, $fields := .Values.serviceMonitors }}
{{- if (and (hasKey $fields "enabled") ($fields.enabled)) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ lower (printf "%s-%s" (include "openebs-monitoring.fullname" $) $openebsEngine) | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "openebs-monitoring.namespace" $ }}
  labels:
    app: {{ template "openebs-monitoring.name" $ }}-{{ $openebsEngine }}
{{ include "openebs-monitoring.labels" $ | indent 4 }}
spec:
  selector:
{{ toYaml $fields.selector | indent 4 }}
  namespaceSelector:
{{ toYaml $fields.namespaceSelector | indent 4 }}
  endpoints:
    - port: {{ $fields.endpoints.port }}
      path: {{ $fields.endpoints.path }}
{{- if $fields.endpoints.relabelings }}
      relabelings:
{{ toYaml $fields.endpoints.relabelings | indent 8 }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
